unit untConstantes;

interface

const
   TBL_CDSVEN0 = 'TBLCDSVEN0';
   TBL_CDSPAI0 = 'TBLCDSPAI0';
   TBL_CDSCID0 = 'TBLCDSCID0';
   TBL_CDSSEC0 = 'TBLCDSSEC0';
   TBL_CDSMAR0 = 'TBLCDSMAR0';
   TBL_CDSITE0 = 'TBLCDSITE0';
   TBL_CDSUSR0 = 'TBLCDSUSR0';

   ID_CDSVEN0 = 'IDVENDEDOR';
   ID_CDSPAI0 = 'IDPAIS';
   ID_CDSCID0 = 'IDCIDADE';
   ID_CDSSEC0 = 'IDSECAO';
   ID_CDSMAR0 = 'IDMARCA';
   ID_CDSITE0 = 'IDITEM';
   ID_CDSUSR0 = 'IDUSUARIO';

implementation

end.
