unit untConstantes;

interface

const
   TBL_CDSVEN0 = 'TBLCDSVEN0';
   TBL_CDSPAI0 = 'TBLCDSPAI0';
   TBL_CDSCID0 = 'TBLCDSCID0';
   TBL_CDSSEC0 = 'TBLCDSSEC0';
   TBL_CDSMAR0 = 'TBLCDSMAR0';
   TBL_CDSITE0 = 'TBLCDSITE0';
   TBL_CDSUSR0 = 'TBLCDSUSR0';
   TBL_CDSMCB0 = 'TBLCDSMCB0';
   TBL_CDSFPG0 = 'TBLCDSFPG0';
   TBL_CDSPRE0 = 'TBLCDSPRE0';
   TBL_CDSCLI0 = 'TBLCDSCLI0';

   ID_CDSVEN0 = 'IDVENDEDOR';
   ID_CDSPAI0 = 'IDPAIS';
   ID_CDSCID0 = 'IDCIDADE';
   ID_CDSSEC0 = 'IDSECAO';
   ID_CDSMAR0 = 'IDMARCA';
   ID_CDSITE0 = 'IDITEM';
   ID_CDSUSR0 = 'IDUSUARIO';
   ID_CDSMCB0 = 'IDMEIOCOB';
   ID_CDSFPG0 = 'IDFORMPAG';
   ID_CDSPRE0 = 'IDTABPRECO';
   ID_CDSCLI0 = 'IDCLIENTE';

   DE_CDSVEN0 = 'VENDEDOR';
   DE_CDSPAI0 = 'PAIS';
   DE_CDSCID0 = 'CIDADE';
   DE_CDSSEC0 = 'SECAO';
   DE_CDSMAR0 = 'MARCA';
   DE_CDSITE0 = 'ITEM';
   DE_CDSUSR0 = 'USUARIO';
   DE_CDSMCB0 = 'MEIOCOB';
   DE_CDSFPG0 = 'FORMPAG';
   DE_CDSPRE0 = 'TABPRECO';
   DE_CDSCLI0 = 'RAZAO';

   GEN_TBLCDSPAI0 = 'GEN_TBLCDSPAI0_IDPAIS';
   GEN_TBLCDSCID0 = 'GEN_TBLCDSCID0_IDCIDADE';
   GEN_TBLCDSCLI0 = 'GEN_TBLCDSCLI0_IDCLIENTE';
   GEN_TBLCDSFPG0 = 'GEN_TBLCDSFPG0_IDFORMPAG';
   GEN_TBLCDSITE0 = 'GEN_TBLCDSITE0_IDITEM';
   GEN_TBLCDSMAR0 = 'GEN_TBLCDSMAR0_IDMARCA';
   GEN_TBLCDSMCB0 = 'GEN_TBLCDSMCB0_IDMEIOCOB';
   GEN_TBLCDSPRE0 = 'GEN_TBLCDSPRE0_IDTABPRECO';
   GEN_TBLCDSSEC0 = 'GEN_TBLCDSSEC0_IDSECAO';
   GEN_TBLCDSUSR0 = 'GEN_TBLCDSUSR0_IDUSUARIO';
   GEN_TBLCDSVEN0 = 'GEN_TBLCDSVEN0_IDVENDEDOR';

implementation

end.
